#!/bin/bash
# Entry script to start Xvfb and set DISPLAY
set -e

# Set the defaults
DEFAULT_ROBOT_DISPLAY_RESOLUTION="1280x1024x24"
DEFAULT_DISPLAY=":99"

DEFAULT_WEB_IMAGE_HOST_NAME="web"
DEFAULT_WEB_IMAGE_PORT="8080"

DEFAULT_ROBOT_LOG_LEVEL="INFO" # Available levels: TRACE, DEBUG, INFO (default), WARN, NONE (no logging)
DEFAULT_ROBOT_TESTS="/robot-tests"
DEFAULT_ROBOT_USER="mustermax@htw-berlin.de"
DEFAULT_ROBOT_BROWSER="firefox"
DEFAULT_ROBOT_OUTPUTDIR="/robot-test-output"

# Use default if none specified as env var
ROBOT_DISPLAY_ROBOT_DISPLAY_RESOLUTIONOLUTION=${ROBOT_DISPLAY_ROBOT_DISPLAY_RESOLUTIONOLUTION:-$DEFAULT_ROBOT_DISPLAY_RESOLUTION}
DISPLAY=${DISPLAY:-$DEFAULT_DISPLAY}

WEB_IMAGE_HOST_NAME=${WEB_IMAGE_HOST_NAME:-$DEFAULT_WEB_IMAGE_HOST_NAME}
WEB_IMAGE_PORT=${WEB_IMAGE_PORT:-$DEFAULT_WEB_IMAGE_PORT}
WEB_URL=${WEB_URL:-"http://$DEFAULT_WEB_IMAGE_HOST_NAME:$DEFAULT_WEB_IMAGE_PORT/#/"}

ROBOT_USER=${ROBOT_USER:-$DEFAULT_ROBOT_USER}
ROBOT_BROWSER=${ROBOT_BROWSER:-$DEFAULT_ROBOT_BROWSER}

ROBOT_TESTS=${ROBOT_TESTS:-$DEFAULT_ROBOT_TESTS}
ROBOT_OUTPUTDIR=${ROBOT_OUTPUTDIR:-$DEFAULT_ROBOT_OUTPUTDIR}
ROBOT_LOG_LEVEL=${ROBOT_LOG_LEVEL:-$DEFAULT_ROBOT_LOG_LEVEL}

# Start Xvfb
echo -e "Starting Xvfb on DISPLAY ${DISPLAY} with ROBOT_DISPLAY_RESOLUTION ${ROBOT_DISPLAY_RESOLUTION}"
Xvfb ${DISPLAY} -ac -screen 0 ${ROBOT_DISPLAY_RESOLUTION} +extension RANDR &
export DISPLAY=${DISPLAY}

# Execute tests
echo -e "Executing robot tests at log level ${ROBOT_LOG_LEVEL}"
robot -v browser:${ROBOT_BROWSER} --outputdir ${ROBOT_OUTPUTDIR} --loglevel ${ROBOT_LOG_LEVEL} \
    -v user:${ROBOT_USER} -v url:${WEB_URL} ${ROBOT_TESTS}

# Stop Xvfb
kill -9 $(pgrep Xvfb)