web:
  build: .
  command: npm run dev
  volumes:
    - "./app:/src/app"
  ports:
    - "80:8080"
    - "3001:3001"
test:
  build: .
  dockerfile: Dockerfile.test
  volumes:
    - "/robot-tests/devicer-testsuite"
  links:
    - "web"