version: '2'
services:
  web:
    image: "htw-berlin/devicer-web"
    build: .
    command: npm run dev
    volumes:
      - "./app/:/src/app/"
    ports:
      - "80:8080"
      - "3001:3001"
  test:
    image: "htw-berlin/devicer-robot"
    build: ./robot-tests/
    volumes:
      - "./robot-tests/devicer-testsuite/:/robot-tests/"
      - "./app/static/test-output/:/robot-test-output/"
    environment:
      - ROBOT_BROWSER=firefox
      - ROBOT_DISPLAY_RESOLUTION=1920x1080x24
      - ROBOT_USER=maxmustermaennchen@mail.de
    links:
      - web
    depends_on:
      - "web"
