version: '1'
services:
  web:
    image: "htw-berlin/devicer-web"
    build: .
    command: npm run dev
    volumes:
      - "./app:/src/app"
    ports:
      - "80:8080"
      - "3001:3001"
  test:
    image: "htw-berlin/devicer-robot"
    build: ./robot-tests/
    command: echo "robot tests are ready to run"
    volumes:
      - "/robot-tests/devicer-testsuite"
    links:
      - "web"